import type { Metadata } from "next";
import {Inter, Spline_Sans} from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const spline = Spline_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-spline',
})

export const metadata: Metadata = {
  title: "Tiny Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${spline.variable}`}>
      <body
        className=""
      >
        <div className="w-full h-20 bg-gray-700 content-center">
          <h4 className="font-spline text-white w-1/4 ml-20 text-4xl">
            My Tiny Expense Tracker
          </h4>
        </div>
        {children}
      </body>
    </html>
  );
}
